Update passwd-gen.py
GabziDev/password-generator pull request #3
Opened 2022-09-14 17:11 UTC by dBasdk

2022-09-15 06:36 UTC, AiroPi requested changes

2022-09-15 06:36 UTC, AiroPi commented on passwd-gen.py
>  import random
`random` should NOT be used to generate passwords for security reasons.
For this type of cases, please consider using `secrets`.

2022-09-15 06:36 UTC, AiroPi commented on passwd-gen.py
> +print("\n> Github: github.com/GabziDev")
Input where present to prevent the window to be closed after the program run (happen when you open the programme directly for files explorer).
However, the variable x is not needed, and you should juste replace print by input.

2022-09-15 06:36 UTC, AiroPi commented on passwd-gen.py
> +print("\n> Github: github.com/GabziDev")
DON'T forget to put a blank line at the end of the file. It's a better practice :)

2022-09-15 06:36 UTC, AiroPi commented on passwd-gen.py
>      exit()
Use sys.exit instead of exit().
And add a return code 0 to tell the programs exited with failure (`sys.exit(0)`)

2022-09-18 19:35 UTC, janast3369 approved these changes

2022-09-18 19:39 UTC, janast3369 commented on passwd-gen.py
>      exit()
After I think that in his case an `exit(1)` is just preferable to be able to copy the password before closing the program. But it could also use a function to automatically copy the content to the clipboard 🤔

2022-09-20 16:55 UTC, merged